# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semantic-cleaning',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/semantic-cleaning',
                'lib_path': 'semantic_cleaning'},
  'syms': {'semantic_cleaning.core': {'semantic_cleaning.core.foo': ('core.html#foo', 'semantic_cleaning/core.py')}}}
