# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semantic-cleaning',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/semantic-cleaning',
                'lib_path': 'semantic_cleaning'},
  'syms': { 'semantic_cleaning.core': { 'semantic_cleaning.core.compute_embeddings': ( 'core.html#compute_embeddings',
                                                                                       'semantic_cleaning/core.py'),
                                        'semantic_cleaning.core.deduplicate_dataset': ( 'core.html#deduplicate_dataset',
                                                                                        'semantic_cleaning/core.py'),
                                        'semantic_cleaning.core.deduplicate_embeddings': ( 'core.html#deduplicate_embeddings',
                                                                                           'semantic_cleaning/core.py'),
                                        'semantic_cleaning.core.mean_pooling': ('core.html#mean_pooling', 'semantic_cleaning/core.py'),
                                        'semantic_cleaning.core.preprocess_data': ( 'core.html#preprocess_data',
                                                                                    'semantic_cleaning/core.py')}}}
